name: 'Print Environment Variables'
description: 'A GitHub Action to print environment variables'
inputs:
  envs:
    description: 'Comma-separated list of environment variables to print'
    required: false
    default: 'ALL'

runs:
  using: 'composite'
  steps:
    - run: |
        if [ "${{ inputs.envs }}" = "ALL" ]; then
          # Print all environment variables
          env
        else
          # Split the comma-separated list into an array and iterate through it
          IFS=',' read -ra VAR_LIST <<< "${{ inputs.envs }}"
          for var in "${VAR_LIST[@]}"; do
            echo "$var=${!var}"
          done
        fi
      shell: bash
