name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Print Env Action
        uses: rahkumar56/gha_printenvvariable/.github/actions/print-env@main
        with:
          envs: 'VAR1,VAR2,ONE_LINE_SECRET,MULTILINE_SECRET,JSON_SECRET,FILE_SECRET'
        env:
          VAR1: 'value1'
          VAR2: 'value2'
          ONE_LINE_SECRET: ${{ secrets.ONE_LINE_SECRET }}
          MULTILINE_SECRET: ${{ secrets.MULTILINE_SECRET }}
          JSON_SECRET: ${{ secrets.JSON_SECRET }}
          FILE_SECRET: ${{ secrets.FILE_SECRET }}

      - name: Print Multiline Secret
        run: |
          echo "Multiline Secret:"
          echo "${{ secrets.MULTILINE_SECRET }}" | while read -r line; do
            echo "$line"
          done
        shell: bash

      - name: Handle File Secret
        run: |
          echo "${{ secrets.FILE_SECRET }}" > secret_file.txt
          cat secret_file.txt
        shell: bash

      - name: Print JSON Secret
        run: |
          echo "JSON Secret:"
          echo "${{ secrets.JSON_SECRET }}" | jq '.'
        shell: bash
